### PR TITLE
Added loading icon to UserSearch

### PR DESCRIPTION
**Pull request by VincentLeighton**
Added library for loading icon in package.json

## Description

Added a library for the loading spinner, minor change to css for spacing out spinner. 

## PR Readiness Checklist

* General
    * [x] Verified all changes are related to feature described above (no scope creep)
* Branch Stuff
    * [x] Checked target and base branch (should be feature branch merging INTO `main`)
    * [x] Merged latest `main` into feature branch (so it has latest code)
    * [x] Resolved any conflicts between feature branch and `main`
* Test Stuff
    * [ ] Added unit tests to cover modified / additional code
* GitHub Stuff (on the right 👉)
    * [x] Updated labels
    * [x] Linked issue to which this PR relates
    * [x] Added assignee
    * [x] Added at least one (1) reviewer

### CODE REVIEW

**Comment by jhechtf** [comment]
Material UI has its own icons that would be better in-line with their look/feel

https://material-ui.com/components/icons/#icons

**Comment by Wolven531** [comment]
Yeah, I definitely want to avoid adding Bootstrap (which is a full other UI library) if possible

**Review by Wolven531 — CHANGES_REQUESTED** [review]
Let's pair on this and find a way to accomplish it w/o bootstrap

**Comment by jhechtf** [comment]
I looked some into it, it would be the `CircularProgress` element from Material UI.

**Comment by Wolven531** [comment]
@VincentLeighton and I connected on this today - he'll be using both the Icon that @jhechtf mentioned as well as MUI's Modal component

* MUI Modal docs - https://material-ui.com/components/modal/#modal
* MUI Progress (and Progress Icons) docs - https://material-ui.com/components/progress/#progress

I've run through the branch and stripped out the bootstrap refs

**Comment by Wolven531** [comment]
According to the MUI docs here - https://material-ui.com/components/box/#box - Box is for overriding components. Since we are not doing that, I'm going to advise we do not use Box. I'm going to checkout your branch and give it a shot w/ either Container or Grid and post an update here afterwards

**Review by Wolven531 — APPROVED** [review]
Lgtm, 👍🏻

Nice job, 😀

**Pull request merged**
